$font = Noto Sans Semicondensed

general {
	hide_cursor = false
}

background {
	path = screenshot
	brightness = 0.25
	blur_passes = 3
}

input-field {
	size = 160, 40
	outline_thickness = 1

	check_color = 0xff22242d
	fail_color = 0xffb64630
	inner_color = 0xff181b25
	outer_color = 0xff22242d

	font_color = 0xfffff7e5
	fade_on_empty = false
	rounding = 0

	font_family = $font
	placeholder_text = Password

	dots_size = 0.15
	dots_spacing = 0.3

	position = 0, 0
	halign = center
	valign = center
}
