if [[ " ${HOOKS[*]} " != *" plymouth "* ]]
then
	_hooks=()

	for _hook in "${HOOKS[@]}"
	do
		_hooks+=("${_hook}")

		if [[ "${_hook}" == "systemd" || "${_hook}" == "udev" ]]
		then
			_hooks+=("plymouth")
		fi
	done

	HOOKS=("${_hooks[@]}")

	unset _hook _hooks
fi
